data("setsList")
swiss_protein <- filter_swiss_protein(setsList$swiss_protein, probability = 0.9)
uniprot_id <- swiss_protein$id
GO_tibble <- UNIPROT2GO(uniprot_id = uniprot_id)
swiss_GO <- setsList_protein2setsList_GO(swiss_protein)
hmdb_GO <- setsList_protein2setsList_GO(setsList_protein = setsList$hmdb_protein)

data("example_data")
data("metabolitesList")
example_data <- id_mapping(example_data, from = "kegg_id", "hmdb_id", metabolites_tibble = metabolitesList$hmdb)
enrichmentRes_kstest <- kstest(input = example_data, enrich_tibble = hmdb_GO, adjust = "fdr", thread = 8)
enrichmentRes_kstest <- enrichmentRes_kstest %>% dplyr::filter(pvalue < 0.05) %>% dplyr::arrange(pvalue)
plot_enrichmentRes(enrichmentRes_kstest, top = 30, plot_type = 2)
enrichmentRes_grsa <- grsa(input = example_data, enrich_tibble = hmdb_GO, adjust = "fdr", thread = 8)
enrichmentRes_grsa <- enrichmentRes_grsa %>% dplyr::filter(pvalue < 0.05) %>% dplyr::arrange(pvalue)
plot_compareRes(list(kstest = enrichmentRes_kstest, grsa = enrichmentRes_grsa), top = 30, plot_type = 2)
